"""
MealMemberServing model — stores per-member portion data for joint profile meals.

This table is only populated for meals belonging to joint profile WeeklyPlans.
For solo profile plans, this table has no rows for those meals.

Schema design notes:
  - member_name is denormalized for resilient historical display: if a member's
    UserProfile is later deleted, historical plan data still renders correctly.
  - adjustment is LLM-generated human-readable text (e.g., "half rice, extra salad").
    In Workflow A (Hybrid), this is produced by the LLM formatting step that converts
    LP numeric allocations into natural language. In Workflow B (LLM-only), it comes
    directly from the single-pass LLM response.
  - portion_description optionally includes gram weights for the recipe detail view.
  - calories/protein/carbs/fats/fiber reflect THIS member's share of the meal, not
    the total meal nutrition. The sum of all members' calories for a given meal_id
    approximates (but does not exactly equal) the base Meal.calories, because
    different members receive different portion fractions.
  - UniqueConstraint(meal_id, member_profile_id) prevents duplicate serving records
    per (meal, member) pair. Generation code must DELETE existing rows before
    inserting new ones when regenerating a plan (not upsert).
"""

from sqlalchemy import Column, Integer, Float, String, Text, ForeignKey, UniqueConstraint
from sqlalchemy.orm import relationship
from database import Base


class MealMemberServing(Base):
    """
    Per-member serving allocation for a single meal in a joint profile plan.

    Relationships:
      meal           — parent Meal (many-to-one); back_populates="member_servings"
                       on the Meal side adds the reverse list automatically.
      member_profile — the household member's UserProfile (many-to-one, no backref
                       needed — UserProfile does not require a reverse list of servings).
    """

    __tablename__ = "meal_member_servings"

    # ---------------------------------------------------------------------------
    # Primary Key
    # ---------------------------------------------------------------------------
    id = Column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    # ---------------------------------------------------------------------------
    # Foreign Keys
    # ---------------------------------------------------------------------------
    meal_id = Column(
        Integer,
        ForeignKey("meals.id", ondelete="CASCADE"),
        nullable=False,
        index=True,  # Index required: all serving lookups filter by meal_id (N+1 avoidance)
        comment="Parent meal this serving belongs to. CASCADE ensures cleanup on meal delete.",
    )
    member_profile_id = Column(
        Integer,
        ForeignKey("user_profiles.id", ondelete="CASCADE"),
        nullable=False,
        comment="The individual household member's UserProfile id.",
    )

    # ---------------------------------------------------------------------------
    # Display Fields
    # ---------------------------------------------------------------------------
    member_name = Column(
        String(100),
        nullable=False,
        comment=(
            "Denormalized member name for display. Stored here rather than joined from "
            "UserProfile so that historical plans remain readable even if the member "
            "profile is later deleted."
        ),
    )

    # ---------------------------------------------------------------------------
    # LLM-Generated Adjustment Text
    # ---------------------------------------------------------------------------
    adjustment = Column(
        Text,
        nullable=True,
        comment=(
            "Human-readable portion adjustment generated by the LLM. "
            "Examples: 'half rice, extra salad, add cucumber raita', "
            "'no garnish peanuts, full portion', 'skip rice, double dal'. "
            "In Workflow A, this is produced by the LLM converting LP numeric "
            "allocation fractions into natural language. In Workflow B, it is "
            "produced directly by the single-pass generation prompt."
        ),
    )
    portion_description = Column(
        Text,
        nullable=True,
        comment=(
            "Detailed portion description with gram weights where available. "
            "Shown in the recipe detail/modal view. "
            "Example: '150g basmati rice, 200g dal tadka, 1 full salad bowl (120g)'."
        ),
    )

    # ---------------------------------------------------------------------------
    # Per-Member Nutritional Data (this member's share — not the full meal total)
    # ---------------------------------------------------------------------------
    # In Workflow A (Hybrid): computed as LP allocation fractions × component nutrition.
    # In Workflow B (LLM-only): generated directly by the LLM.
    calories = Column(
        Float,
        nullable=False,
        comment="This member's calorie share for this meal (not the full meal total).",
    )
    protein = Column(
        Float,
        nullable=False,
        comment="This member's protein share in grams.",
    )
    carbs = Column(
        Float,
        nullable=False,
        comment="This member's carbohydrate share in grams.",
    )
    fats = Column(
        Float,
        nullable=False,
        comment="This member's fat share in grams.",
    )
    fiber = Column(
        Float,
        nullable=True,
        default=0,
        comment=(
            "This member's fiber share in grams. "
            "Nullable for backward compatibility; defaults to 0 when not provided."
        ),
    )

    # ---------------------------------------------------------------------------
    # Unique Constraint
    # ---------------------------------------------------------------------------
    # Enforced at the database level so that even raw SQL inserts cannot create
    # duplicate serving records. SQLite raises sqlite3.IntegrityError on violation.
    # The meal plan generation router (Phase 4) must DELETE existing MealMemberServing
    # rows for a meal before inserting fresh ones when regenerating.
    __table_args__ = (
        UniqueConstraint(
            "meal_id",
            "member_profile_id",
            name="uq_meal_member_serving",
        ),
    )

    # ---------------------------------------------------------------------------
    # Relationships
    # ---------------------------------------------------------------------------
    # back_populates="member_servings" pairs with the explicit relationship added
    # to the Meal model in Task 1.3. Both sides must use back_populates (not backref)
    # so the relationship is visible when reading either model file.
    meal = relationship(
        "Meal",
        back_populates="member_servings",
    )
    member_profile = relationship(
        "UserProfile",
        # No backref — UserProfile does not need a reverse collection of servings.
        # foreign_keys must be specified explicitly because this model has two FKs
        # that both eventually resolve through user_profiles (meal_id reaches
        # user_profiles via meals→daily_plans→weekly_plans→user_profiles, and
        # member_profile_id references user_profiles directly). SQLAlchemy needs
        # the explicit hint to avoid an AmbiguousForeignKeysError.
        foreign_keys=[member_profile_id],
    )

    def __repr__(self):
        return (
            f"<MealMemberServing("
            f"id={self.id}, "
            f"meal_id={self.meal_id}, "
            f"member='{self.member_name}', "
            f"calories={self.calories}"
            f")>"
        )
